services:
  postgres:
    image: postgres:16
    container_name: my_nest_postgres
    environment:
      POSTGRES_USER: nestcource
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nestcource -d tasks"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  api:
    build: .
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: '5432'
      DB_USER: nestcource
      DB_PASSWORD: postgres
      DB_NAME: tasks
      PORT: 8080
    ports:
      - "8080:8080"   # <-- map host port 8080 to container port 8080
    restart: on-failure

volumes:
  postgres_data: