### Variables
@baseURL = http://localhost:3000
@content-type = application/json

###
# @name createNewTask
POST {{baseURL}}/tasks
Content-Type: {{content-type}}

{
    "title": "Learn NestJS",
    "description": "Complete NestJS project",
    "status": "OPEN",
    "userId": "bfa4cdb7-77b8-4913-8bd7-0a52b1d7fd42",
    "labels": [
        {
            "name": "backend"
        },
        {
            "name": "nestjs"
        }
    ]
}

### Set taskId variable
@taskId = {{createNewTask.response.body.$.id}}


{{baseURL}}
###
GET {{baseURL}}/tasks

###Get One Task
GET {{baseURL}}/tasks/{{taskId}}


### Test invalid status
POST {{baseURL}}/tasks
Content-Type: {{content-type}}

{
    "title": null,
    # "description": "Complete NestJS project",
    "status": "XXX"
}

### Update task
PATCH {{baseURL}}/tasks/{{taskId}}
Content-Type: {{content-type}}

{
    "status": "OPEN",
    "labels": []
}

### Delete task
DELETE {{baseURL}}/tasks/{{taskId}}

### Add Task Labels
# @name addTaskLabels
POST {{baseURL}}/tasks/{{taskId}}/labels
Content-Type: {{content-type}}

[
    {
        "name": "urgent"
    },
    {
        "name": "high priority"
    }
]

### Remove Task Labels
# @name removeTaskLabels
DELETE {{baseURL}}/tasks/{{taskId}}/labels
Content-Type: {{content-type}}

[
    "backend",
    "urgent"
]